version: "3.7"

services:
  cfml:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SSL_PORT: 8443
      #javaVersion: openjdk9
      javaVersion: openjdk11